/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as IndexImport } from './routes/index'
import { Route as appLoginIndexImport } from './routes/(app)/login/index'
import { Route as appDashboardIndexImport } from './routes/(app)/dashboard/index'

// Create/Update Routes

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const appLoginIndexRoute = appLoginIndexImport.update({
  id: '/(app)/login/',
  path: '/login/',
  getParentRoute: () => rootRoute,
} as any)

const appDashboardIndexRoute = appDashboardIndexImport.update({
  id: '/(app)/dashboard/',
  path: '/dashboard/',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/(app)/dashboard/': {
      id: '/(app)/dashboard/'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof appDashboardIndexImport
      parentRoute: typeof rootRoute
    }
    '/(app)/login/': {
      id: '/(app)/login/'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof appLoginIndexImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof appDashboardIndexRoute
  '/login': typeof appLoginIndexRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof appDashboardIndexRoute
  '/login': typeof appLoginIndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/(app)/dashboard/': typeof appDashboardIndexRoute
  '/(app)/login/': typeof appLoginIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/dashboard' | '/login'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/dashboard' | '/login'
  id: '__root__' | '/' | '/(app)/dashboard/' | '/(app)/login/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  appDashboardIndexRoute: typeof appDashboardIndexRoute
  appLoginIndexRoute: typeof appLoginIndexRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  appDashboardIndexRoute: appDashboardIndexRoute,
  appLoginIndexRoute: appLoginIndexRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/(app)/dashboard/",
        "/(app)/login/"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/(app)/dashboard/": {
      "filePath": "(app)/dashboard/index.tsx"
    },
    "/(app)/login/": {
      "filePath": "(app)/login/index.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
